version: '3.8'
services:
  database:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: chat_app_development
  development:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
